# https://nixpacks.com/docs/configuration/file

# set up some variables to minimize annoyance
[variables]
    NPM_CONFIG_UPDATE_NOTIFIER = 'false' # the update notification is relatively useless in a production environment
    NPM_CONFIG_FUND = 'false' # the fund notification is also pretty useless in a production environment
#    CADDY_VERSION = '2.7.5' # specify the caddy version to use here, without a 'v' prefix. https://github.com/caddyserver/caddy/releases
    NODE_VERSION = 'v21.2.0' # specify the caddy version to use here, without a 'v' prefix. https://github.com/caddyserver/caddy/releases
    cmd = 'node -v'

# download and untar caddy
#[phases.caddy]
#    dependsOn = ['setup'] # make sure this phase runs after the default 'setup' phase
#    cmds = [
#        'curl -fsSLo caddy.tar.gz "https://github.com/caddyserver/caddy/releases/download/v${CADDY_VERSION}/caddy_${CADDY_VERSION}_linux_amd64.tar.gz"', # download the caddy release specified by 'CADDY_VERSION' from GitHub
#        'tar -zxvf caddy.tar.gz caddy', # only extract 'caddy' from the tarball
#        'chmod +x caddy' # enable file execution for caddy, needed to execute downloaded files
#    ]

# download and untar node
[phases.node]
    dependsOn = ['setup'] # make sure this phase runs after the default 'setup' phase
    cmds = [
        'node -v',
        'curl -fsSLo node.tar.gz https://nodejs.org/dist/${NODE_VERSION}/node-${NODE_VERSION}-linux-x64.tar.gz', # download the node release specified by 'NODE_VERSION' from nodejs.org
        'tar -zxvf node.tar.gz node-${NODE_VERSION}-linux-x64/bin/node', # only extract node from the tarball
    ]

# copy node and build artifacts to a new image and start the node server
[start]
    runImage = 'ubuntu:20.04' # use a new ubuntu image to run the caddy server in
    onlyIncludeFiles = ['node-${NODE_VERSION}-linux-x64/bin/node', 'dist'] # copy only the needed files and folders into the new image (Angular is configured to build to a 'dist' folder)
    cmds = ['./node-v21.2.0-linux-x64/bin/node dist/myApp/server/main.js'] # start
