# https://nixpacks.com/docs/configuration/file

# set up some variables to minimize annoyance
[variables]
    NPM_CONFIG_UPDATE_NOTIFIER = 'false' # the update notification is relatively useless in a production environment
    NPM_CONFIG_FUND = 'false' # the fund notification is also pretty useless in a production environment

[phases.build]
    cmds = ['npm run build:ssr']

# copy node and build artifacts to a new image and start the node server
[start]
    runImage = 'debian' # use a new ubuntu image to run the caddy server in
    onlyIncludeFiles = ['dist'] # copy only the needed files and folders into the new image (Angular is configured to build to a 'dist' folder)
    cmd = 'npm serve:ssr' # start
